In [18]:
import pandas as pd
import datetime

In [19]:
array = 'cabled'
data_file = '/Users/knuth/Documents/ooi/repos/github/ooi_stats/output/'+array+'/data.csv'
refdes_streams = '/Users/knuth/Documents/ooi/repos/github/ooi_stats/input/'+array+'.csv'
data = pd.read_csv(data_file)
refdes_streams_df = pd.read_csv(refdes_streams)

In [20]:
data = pd.DataFrame(data, columns=['refdes', 'stream', 'timestamp'])
data_temp = pd.DataFrame(data, columns=['refdes', 'stream'])
refdes_streams_df = pd.DataFrame(refdes_streams_df, columns=['refdes', 'stream'])

In [21]:
test = pd.concat([data_temp, refdes_streams_df])

In [4]:

data['platform'] = data['refdes'].str[:8]
data['node'] = data['refdes'].str[:14]

In [5]:
data['start'] = data['timestamp']
data['timestamp'] = pd.to_datetime(data['timestamp'])
data['end'] = data['timestamp'] + datetime.timedelta(seconds=86400)

In [6]:
data = pd.DataFrame(data, columns=['platform', 'node', 'refdes', 'stream', 'start', 'end'])

In [7]:
platform = data.drop(['refdes','stream', 'node'],axis = 1)

In [8]:
platform

       platform       start        end
0      RS03ECAL  2013-07-27 2013-07-28
1      RS03ECAL  2014-09-03 2014-09-04
2      RS03ECAL  2014-09-07 2014-09-08
3      RS03ECAL  2014-09-10 2014-09-11
4      RS03ECAL  2014-09-11 2014-09-12
5      RS03ECAL  2014-09-06 2014-09-07
6      RS03ECAL  2014-09-15 2014-09-16
7      RS03ECAL  2014-09-12 2014-09-13
8      RS03ECAL  2014-09-09 2014-09-10
9      RS03ECAL  2014-09-04 2014-09-05
10     RS03ECAL  2014-09-05 2014-09-06
11     RS03ECAL  2014-09-14 2014-09-15
12     RS03ECAL  2014-09-08 2014-09-09
13     RS03ECAL  2014-09-13 2014-09-14
14     RS03ECAL  2014-09-18 2014-09-19
15     RS03ECAL  2014-09-22 2014-09-23
16     RS03ECAL  2014-09-26 2014-09-27
17     RS03ECAL  2014-09-19 2014-09-20
18     RS03ECAL  2014-09-16 2014-09-17
19     RS03ECAL  2014-09-23 2014-09-24
20     RS03ECAL  2014-09-27 2014-09-28
21     RS03ECAL  2014-09-17 2014-09-18
22     RS03ECAL  2014-09-20 2014-09-21
23     RS03ECAL  2014-09-24 2014-09-25
24     RS03ECAL  2014-09-28 2014-09-29
25     RS03ECAL  2014-09-21 2014-09-22
26     RS03ECAL  2014-10-03 2014-10-04
27     RS03ECAL  2014-09-30 2014-10-01
28     RS03ECAL  2014-09-25 2014-09-26
29     RS03ECAL  2014-10-01 2014-10-02
...         ...         ...        ...
38559  RS01SLBS  2017-06-19 2017-06-20
38560  RS01SLBS  2017-06-24 2017-06-25
38561  RS01SLBS  2017-06-30 2017-07-01
38562  RS01SLBS  2017-06-21 2017-06-22
38563  RS01SLBS  2017-07-03 2017-07-04
38564  RS01SLBS  2017-06-29 2017-06-30
38565  RS01SLBS  2017-06-25 2017-06-26
38566  RS01SLBS  2017-07-07 2017-07-08
38567  RS01SLBS  2017-06-27 2017-06-28
38568  RS01SLBS  2017-07-02 2017-07-03
38569  RS01SLBS  2017-06-26 2017-06-27
38570  RS01SLBS  2017-06-28 2017-06-29
38571  RS01SLBS  2017-07-05 2017-07-06
38572  RS01SLBS  2017-07-10 2017-07-11
38573  RS01SLBS  2017-07-06 2017-07-07
38574  RS01SLBS  2017-07-04 2017-07-05
38575  RS01SLBS  2017-07-01 2017-07-02
38576  RS01SLBS  2017-07-08 2017-07-09
38577  RS01SLBS  2017-07-14 2017-07-15
38578  RS01SLBS  2017-07-18 2017-07-19
38579  RS01SLBS  2017-07-11 2017-07-12
38580  RS01SLBS  2017-07-19 2017-07-20
38581  RS01SLBS  2017-07-09 2017-07-10
38582  RS01SLBS  2017-07-13 2017-07-14
38583  RS01SLBS  2017-07-12 2017-07-13
38584  RS01SLBS  2017-07-20 2017-07-21
38585  RS01SLBS  2017-07-15 2017-07-16
38586  RS01SLBS  2017-07-16 2017-07-17
38587  RS01SLBS  2017-07-17 2017-07-18
38588  RS01SLBS  2017-07-21 2017-07-22

[38589 rows x 3 columns]